backend:
  name: github
  repo: dtaman1muncar/web # Ganti dengan "Username/Nama-Repo-GitHub-Anda"
  branch: main # Atau "master" sesuai cabang utama di GitHub Anda

media_folder: "images" # Folder tempat gambar disimpan
public_folder: "images"

collections:
  - name: "cerita_baik"
    label: "Cerita Baik & Kegiatan"
    folder: "content/cerita" # Folder penyimpanan file teks artikel baru
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul Artikel", name: "title", widget: "string" }
      - { label: "Penulis", name: "author", widget: "string", default: "Agus Suyatno, S.Kom" }
      - { label: "Tanggal Terbit", name: "date", widget: "datetime" }
      - { label: "Kategori", name: "category", widget: "select", options: ["Wirausaha Kuliner", "Tata Rias & MUA", "Pelatihan Vokasi", "Kreativitas Produk", "Pelestarian Budaya", "Kewirausahaan Ramadan"] }
      - { label: "Foto Utama", name: "thumbnail", widget: "image" }
      - { label: "Ringkasan Singkat (Pratinjau Kartu)", name: "excerpt", widget: "text" }
      - { label: "Isi Cerita Lengkap", name: "body", widget: "markdown" }
